# ->->->->-> Primary <-<-<-<-<-
arch: "vgg16_bn"
exp_name: "temp"
result_dir: "./trained_models"
num_classes: 10
exp_mode: "pretrain"
layer_type: "dense"
init_type: "kaiming_normal"


# ->->->->-> Pruning <-<-<-<-<-
k: 0.5

# ->->->->-> Train <-<-<-<-<-
trainer: "base"
epochs: 1
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1


# ->->->->-> Eval <-<-<-<-<-
val_method:  hessian


# ->->->->-> Dataset <-<-<-<-<-
dataset: CIFAR10
batch_size: 128
test_batch_size: 1
data_dir: "./datasets"
data_fraction: 1.0

# ->->->->-> Semi-supervised training <-<-<-<-<-
semisup_data: "tinyimages"
semisup_fraction: 1.0


# ->->->->-> Adv <-<-<-<-<-
epsilon: 0.1
num_steps: 30
step_size: 0.0078
clip_min: 0
clip_max: 1
distance: "l_inf"
beta: 6.0


# ->->->->-> Misc <-<-<-<-<-
gpu: "0"
seed: 1234
print_freq: 100